language: elixir
elixir:
  - 1.4.5
otp_release:
  - '20.0'
addons:
  postgresql: '9.5'

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

env:
  global:
    - MIX_ENV=test
    - DATABASE_NAME=travis_ci_test
  matrix:
    - TEST_FOLDER=.
    - TEST_FOLDER=./apps/churchify
    - TEST_FOLDER=./apps/churchify_web

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd $TEST_FOLDER
  - mix ecto.migrate
script:
  - mix test.cover
