web:
  build: .
  command: elixir --erl "-smp disable" -S mix phx.server
  environment:
    - PORT=4000
    - PG_HOST=postgres
    - PG_USERNAME=postgres
    - PG_PASSWORD=postgres
    - SECRET_KEY_BASE=tn0eZZr56FsC1BdBmQt8y5UzmUFDd2aQx0/ZnY/NgPW0ZZiboK6bDJK0GUOujslH
  volumes:
    - .:/app
    - /app/apps/churchify_web/assets/node_modules
  ports:
    - 4000:4000
  links:
    - postgres

postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=postgres
  ports:
    - 5432
